/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UseCases;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author joab
 */

public class EnviarImagem extends javax.swing.JFrame {

    /**
     * Creates new form EnviarImagem
     */
    BufferedImage imagem;

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.The content of this method is always
 regenerated by the Form Editor.
     * @return
     */

    public BufferedImage escolherImagem() {
        
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 160, 160);        

            } catch (Exception ex) {
               //System.out.println(ex.printStackTrace().toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
        return imagem;
    }

    public void salvarImagem(String nome) {
        try {
            String caminho = getClass().getResource("../imagensProdutos/").toString().substring(5);
            File outputfile = new File(caminho + nome + ".jpg");
            ImageIO.write(imagem, "jpg", outputfile);
            JOptionPane.showMessageDialog(rootPane, "Imagem enviada com sucesso");
        } catch (IOException ex) {
            Logger.getLogger(EnviarImagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}